 
# This will run on Travis' 'new' container-based infrastructure
sudo: false 

# Blacklist
branches:
  only:
    - minh-thuc_dev

# Install dependencies
addons:
  apt:
    packages:
      - doxygen

# Build your code e.g. by calling make
script:
  - doxygen ./doxygen/Doxyfile

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dox_control_arm_ALD5/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: 
      - minh-thuc_dev