language: cpp
# This will run on Travis' 'new' container-based infrastructure
sudo: required 

jobs:
  include:  
    - stage: tests
      name: unittest
      # Install dependencies
      addons:
        apt:
          packages:
            - doxygen
            - cmake
            - libevdev-dev
            - libsdl2-dev
            - libboost-dev
            - libboost-test-dev
            - libmicrohttpd-dev
      # Build code
      before-script:
        - ./build.sh 
        - cd test/ && ./run.sh all && cd ..
      script:
        - doxygen ./doxygen/Doxyfile
        - cd test/bin/ && ./unittest --log_level=all
    - name: cpplint test coding-style
      language: python
      python:
        - "3.8"
      install:
        - pip3 install cpplint
      script: 
        - cpplint --recursive --filter=-whitespace/line_length,-runtime/references ./src
        - cpplint --recursive --filter=-whitespace/line_length,-runtime/references ./includes
    - stage: deploy
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: doxygen/dox_control_arm_ALD5/html
        github_token: $GH_REPO_TOKEN
        on:
          branch: 
            - master
