language: cpp
# This will run on Travis' 'new' container-based infrastructure
sudo: required 

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - cmake
      - libevdev-dev
      - libsdl2-dev
      - libboost-dev
      - libboost-test-dev
      - libmicrohttpd-dev
      - python3
install:
  - pip3 install cpplint
# Build code
before-script:
  - ./build.sh 
  - cd test/ && ./run.sh all && cd ..
script:
  - doxygen ./doxygen/Doxyfile

jobs:
  include:  
    - stage: test
    - name: unittest
      script: cd test/bin/ && ./unittest --log_level=all
    - name: cpplint test coding-style
      script: cpplint --recursive --filter=-whitespace/line_length,-runtime/references ./src
      script: cpplint --recursive --filter=-whitespace/line_length,-runtime/references ./includes
    - stage: deploy
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: doxygen/dox_control_arm_ALD5/html
        github_token: $GH_REPO_TOKEN
        on:
          branch: 
            - master
