language: python

python:
  - "3.8"

# Install dependencies
install:
  - pip3 install cpplint

# Build your code e.g. by calling make
script:
  - cpplint --recursive --filter=-runtime/references ./includes
  - cpplint --recursive --filter=-runtime/references ./src
