 
# This will run on Travis' 'new' container-based infrastructure
sudo: false 

# Install dependencies
addons:
  apt:
    packages:
      - doxygen

# Build your code
script:
  - doxygen ./doxygen/Doxyfile

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doxygen/dox_control_arm_ALD5/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: 
      - master