 
# # This will run on Travis' 'new' container-based infrastructure
# sudo: false 

# # Blacklist
# branches:
#   only:
#     - minh-thuc_dev

# # Install dependencies
# addons:
#   apt:
#     packages:
#       - doxygen

# # Build your code e.g. by calling make
# script:
#   - doxygen ./doxygen/Doxyfile

# # Generate and deploy documentation
# deploy:
#   provider: pages
#   skip_cleanup: true
#   local_dir: doxygen/dox_control_arm_ALD5/html
#   github_token: $GH_REPO_TOKEN
#   on:
#     branch: 
#       - minh-thuc_dev

language: cpp
# This will run on Travis' 'new' container-based infrastructure
sudo: required 

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - cmake
      - libevdev-dev
      - libsdl2-dev
      - libboost-dev
      - libboost-test-dev
      - libmicrohttpd-dev
# Build code
install:
  - ./build.sh
  - cd test/ && ./run.sh all
jobs:
  include:
    - stage: generate doxygen
      script: doxygen ./doxygen/Doxyfile
    - stage: unit test
      script: cd bin/ && ./unittest --log_level=all
    - stage: cpplint test coding-style
      script: cpplint --recursive --filter=-whitespace/line_length,-runtime/references ./src
      script: cpplint --recursive --filter=-whitespace/line_length,-runtime/references ./includes
    - stage: deploy
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: doxygen/dox_control_arm_ALD5/html
        github_token: $GH_REPO_TOKEN
        on:
          branch: 
            - master
            